
export const SHOPIFY_CHECKOUT_URL_COOKIE = process.env.NEXT_PUBLIC_SHOPIFY_CHECKOUT_URL_COOKIE

export const SHOPIFY_COOKIE_EXPIRE = 90

export const API_URL = process.env.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN

export const SHOPIFY_CHECKOUT_ID_COOKIE = process.env.NEXT_PUBLIC_SHOPIFY_CHECKOUT_COOKIE_ID

export const ADMIN_ACCESS_TOKEN = process.env.NEXT_PUBLIC_SHOPIFY_ADMIN_ACCESS_TOKEN

export const ADMIN_API_KEY = process.env.NEXT_PUBLIC_SHOPIFY_ADMIN_API_KEY

export const ADMIN_API_SECLET_KEY = process.env.NEXT_PUBLIC_SHOPIFY_ADMIN_API_SECLET_KEY

export const STOREFRONT_ACCESS_TOKEN = process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCCESS_TOKEN