

const DEVLOPMENT = true
const NGROK_URL = " https://c0d3-240b-c020-4c2-64ee-e07a-5f27-2c4d-9f1b.jp.ngrok.io"

export const HOSTING_URL = DEVLOPMENT ? NGROK_URL :  process.env.NEXT_PUBLIC_HOSTING_URL
export const SHOPIFY_ADMIN_API_URL = process.env.NEXT_PUBLIC_SHOPIFY_ADMIN_API_URL
export const SHOPIFY_STOREFRONT_API_URL = process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_API_URL

export const SHOPIFY_COOKIE_EXPIRE = 90
export const SHOPIFY_CHECKOUT_URL_COOKIE = process.env.NEXT_PUBLIC_SHOPIFY_CHECKOUT_URL_COOKIE
export const SHOPIFY_CHECKOUT_ID_COOKIE = process.env.NEXT_PUBLIC_SHOPIFY_CHECKOUT_COOKIE_ID

export const SHOPIFY_ADMIN_ACCESS_TOKEN = process.env.NEXT_PUBLIC_SHOPIFY_ADMIN_ACCESS_TOKEN
export const SHOPIFY_ADMIN_API_KEY = process.env.NEXT_PUBLIC_SHOPIFY_ADMIN_API_KEY
export const SHOPIFY_ADMIN_API_SECLET_KEY = process.env.NEXT_PUBLIC_SHOPIFY_ADMIN_API_SECLET_KEY
export const SHOPIFY_STOREFRONT_ACCESS_TOKEN = process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCCESS_TOKEN